export const COIN_NAMES_FA = Object.freeze({
	bitcoin: "بیت‌کوین",
	ethereum: "اتریوم",
	tether: "تتر",
	binancecoin: "بایننس‌کوین",
	ripple: "ریپل",
	solana: "سولانا",
	"usd-coin": "یو‌اس‌دی کوین",
	dogecoin: "دوج‌کوین",
	cardano: "کاردانو",
	tron: "ترون",
	chainlink: "چین‌لینک",
	avalanche: "آوالانچ",
	stellar: "استلار",
	"shiba-inu": "شیبا اینو",
	sui: "سویی",
	toncoin: "تون‌کوین",
	polkadot: "پولکادات",
	litecoin: "لایت‌کوین",
	"bitcoin-cash": "بیت‌کوین کش",
	hedera: "هدرا",
	hyperliquid: "هایپرلیکویید",
	monero: "مونرو",
	pepe: "پپه",
	uniswap: "یونی‌سواپ",
	aave: "آوه",
	aptos: "آپتوس",
	near: "نیر",
	"internet-computer": "اینترنت کامپیوتر",
	"crypto-com-chain": "کرونوس",
	vechain: "وی‌چین",
	"matic-network": "پالیگان",
	"wrapped-bitcoin": "بیت‌کوین رپد",
	dai: "دای",
	okb: "اوکی‌بی",
	mantle: "منتل",
	bittensor: "بیت‌تنسور",
	"render-token": "رندر",
	filecoin: "فایل‌کوین",
	cosmos: "کازمس",
	arbitrum: "آربیتروم",
	optimism: "آپتیمیزم",
	"injective-protocol": "اینجکتیو",
});
